### ISSUE TITLE
医院列表页物资类型筛选器筛选逻辑不符合预期，取消勾选未正常工作

### ISSUE THREAD

**Issue by wfnuser** [WuhanZhuRong/DonationChannel#15]
![image](https://user-images.githubusercontent.com/8191686/73603705-6133a280-45c1-11ea-8ad8-413636c255fa.png)
如果在上图状态取消勾选医用耗材，会进入下图状态
![image](https://user-images.githubusercontent.com/8191686/73603718-80cacb00-45c1-11ea-85f5-a66417ae7904.png)

**Comment by wfnuser** [comment]
@williamzly  这个你看下？

**Comment by williamzly** [comment]
ok



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mark Huang <notifications@github.com&gt;
发送时间: 2020年2月2日 13:40
收件人: WuhanZhuRong/DonationChannel <DonationChannel@noreply.github.com&gt;
抄送: William <4269946@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[WuhanZhuRong/DonationChannel] 医院列表页物资类型筛选器筛选逻辑不符合预期，取消勾选未正常工作 (#15)




@williamzly  这个你看下？
