### ISSUE TITLE
Logo 调整

### ISSUE THREAD

**Issue by NeverMin** [WuhanZhuRong/DonationChannel#21]
* github 上展示的 LOGO 下方的汉字再往两边调整, 上面宽下面窄, 看上去摇摇欲坠.
![image](https://user-images.githubusercontent.com/2797432/73607122-36f7da00-45ed-11ea-9fcf-1b762699a32e.png)

* favicon 需要一个透明背景
![favicon](https://user-images.githubusercontent.com/2797432/73607400-986d7800-45f0-11ea-85b0-8340a965d3bc.png)

Update: 已和 @xiaoyi731 沟通调整, 如下:
![logo_zhurong](https://user-images.githubusercontent.com/2797432/73607457-32cdbb80-45f1-11ea-930e-46b8d881c071.png)

[download here](https://github.com/WuhanZhuRong/DonationChannel/files/4143921/logo_zhurong.zip)

**Comment by xiaoyi731** [comment]
祝融Icon 128*128改32*32
[祝融icon_画板 1.svg.zip](https://github.com/WuhanZhuRong/DonationChannel/files/4144219/icon_.1.svg.zip)
![祝融icon_画板 1](https://user-images.githubusercontent.com/60397107/73608940-a082e300-4603-11ea-9813-856d60efdc28.png)

**Comment by NeverMin** [comment]
updated: 公众号二维码
![祝融中国](https://user-images.githubusercontent.com/2797432/73611086-44c35480-4619-11ea-9e8d-f2ad3ee2a4df.jpg)
