### ISSUE TITLE
每个品类的第一个选项和品类名称重复

### ISSUE THREAD

**Issue by PaperStrange** [WuhanZhuRong/DonationChannel#9]
![页面优化1_20200202](https://user-images.githubusercontent.com/35859795/73602905-5a536280-45b6-11ea-98ec-6d8ec7697765.jpg)

**Comment by PaperStrange** [comment]
### 重要信息: 
- 网址: http://czr.vipdesk.cn/search
- 浏览器版本: 
- 手机/操作系统: 安卓

**Comment by wfnuser** [comment]
之前已经修复了 尚未部署
